version: '3.4'
services:

  eth-api:
    build:
      context: ./../eth-api
      dockerfile: ./../eth-api/eth-api.dockerfile
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-api:/app
    depends_on:
      - redis
      - mongo-for-eth-blocks-reading
      - mongo-for-eth-transactions-reading
      - queue-for-eth-blocks-fetching
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-cron:
    build:
      context: ./../eth-cron
      dockerfile: ./../eth-cron/eth-cron.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-cron:/app
    depends_on:
      - redis
      - queue-for-eth-blocks-storing
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-store:
    build:
      context: ./../eth-store
      dockerfile: ./../eth-store/eth-store.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-store:/app
    depends_on:
      - redis
      - mongo-for-eth-blocks-writing
      - queue-for-eth-blocks-storing
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-req:
    build:
      context: ./../eth-req
      dockerfile: ./../eth-req/eth-req.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-req:/app
    depends_on:
      - queue-for-eth-blocks-fetching
      - queue-for-eth-blocks-storing
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-transactions-req:
    build:
      context: ./../eth-transactions-req
      dockerfile: ./../eth-transactions-req/eth-transactions-req.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-transactions-req:/app
    depends_on:
      - queue-for-eth-transactions-fetching
      - queue-for-eth-blocks-storing
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.db-data/redis/:/data


  mongo-for-eth-blocks-writing:
    build:
      context: ./
      dockerfile: ./mongo.dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eth_blocks
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./.db-data/mongodb/:/data/db
      - ./mongodb-keyfile:/opt/keyfile/mongodb-keyfile
    depends_on:
      mongo-for-eth-blocks-reading:
        condition: service_healthy
    command: --replSet mongoReplicaSet2 --keyFile /opt/keyfile/mongodb-keyfile


  mongo-for-eth-blocks-reading:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: eth_blocks
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./.db-data/mongodb-replica/:/data/db
      - ./mongodb-keyfile:/opt/keyfile/mongodb-keyfile
    command: --replSet mongoReplicaSet2 --keyFile /opt/keyfile/mongodb-keyfile
    healthcheck:
      test: [ "CMD", "mongo", "-u", "admin", "-p", "password123", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 3


  mongo-for-eth-transactions-reading:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: eth_transactions
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./.db-data/mongo-for-eth-transactions-reading/:/data/db


  queue-for-eth-blocks-fetching:
    image: 'rabbitmq:3-management'
    ports:
      - "5673:5672"
      - "15673:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-eth-blocks-fetching/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000


  queue-for-eth-blocks-storing:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-eth-blocks-storing/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000

  queue-for-eth-transactions-fetching:
    image: 'rabbitmq:3-management'
    ports:
      - "5674:5672"
      - "15674:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-eth-transactions-fetching/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000


  queue-for-eth-transactions-storing:
    image: 'rabbitmq:3-management'
    ports:
      - "5675:5672"
      - "15675:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-eth-transactions-storing/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000