version: '3'
services:

  eth-api:
    build:
      context: ./../eth-api
      dockerfile: ./../eth-api/eth-api.dockerfile
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-api:/app
    depends_on:
      - redis
      - mongo
      - queue-for-api
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-cron:
    build:
      context: ./../eth-cron
      dockerfile: ./../eth-cron/eth-cron.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-cron:/app
    depends_on:
      - redis
      - mongo
      - queue-for-storage
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-store:
    build:
      context: ./../eth-store
      dockerfile: ./../eth-store/eth-store.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-store:/app
    depends_on:
      - redis
      - mongo
      - queue-for-storage
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  eth-req:
    build:
      context: ./../eth-req
      dockerfile: ./../eth-req/eth-req.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./../eth-req:/app
    depends_on:
      - queue-for-api
      - queue-for-storage
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1


  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.db-data/redis/:/data


  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eth_blocks
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./.db-data/mongodb/:/data/db


  queue-for-api:
    image: 'rabbitmq:3-management'
    ports:
      - "5673:5672"
      - "15673:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-api/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000


  queue-for-storage:
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./.db-data/queue-for-storage/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_CHANNEL_MAX=10000000